name: Zoek test

on:
  push:
    branches:
      - main
      - Test/zoektest
  pull_request:
    branches:
      - main
      - Test/zoektest

jobs:
  test-android:
    runs-on: ubuntu-latest
    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4

      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI Android workload
        run: dotnet workload install maui-android

      - name: Herstel afhankelijkheden
        run: dotnet restore

      - name: Bouw (Android only)
        run: dotnet build --configuration Release -f net8.0-android --no-restore

      - name: Voer unit tests uit
        run: dotnet test --configuration Release --verbosity normal
