name: Zoek test

on:
  push:
    branches:
      - main
      - Test/zoektest
  pull_request:
    branches:
      - main
      - Test/zoektest

jobs:
  test-android:
    runs-on: ubuntu-latest
    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4

      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI Android workload
        run: dotnet workload install maui-android

      - name: Restore
        run: dotnet restore

      - name: Build (Android only)
        run: dotnet build ./Grocery.App/Grocery.App.csproj -c Release -f net8.0-android --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
